name: smartbiztracker_new
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Dependencies sorted alphabetically
  cached_network_image: ^3.3.1
  camera: ^0.10.5+9
  carousel_slider: ^5.0.0
  cloud_firestore: ^4.15.5
  collection: ^1.17.2
  connectivity_plus: ^5.0.2
  csv: ^6.0.0
  cupertino_icons: ^1.0.6
  device_info_plus: ^9.1.1
  dio: ^5.4.0
  excel: ^4.0.6
  file_picker: ^10.1.9
  firebase_core: ^2.24.2
  fl_chart: ^0.66.0
  flutter_animate: ^4.5.0
  flutter_dotenv: ^5.1.0
  flutter_easyloading: ^3.0.5
  flutter_image_compress: ^2.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^19.2.1
  flutter_native_splash: ^2.3.10
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.0.0
  flutter_slidable: ^3.0.1
  flutter_smart_dialog: ^4.8.0
  flutter_speed_dial: ^7.0.0
  flutter_spinkit: ^5.2.0
  flutter_staggered_animations: ^1.1.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_stripe: ^10.0.0
  flutter_svg: ^2.0.9
  geolocator: ^10.1.0
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.5.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  html: ^0.15.4
  http: ^1.2.0
  image: ^4.1.7
  image_picker: ^1.0.7
  intl: ^0.19.0
  local_auth: ^2.1.8
  logger: ^2.0.2+1
  lottie: ^2.7.0
  package_info_plus: ^4.2.0
  particles_flutter: ^0.1.4
  path: ^1.8.3
  path_provider: ^2.1.2
  pdf: ^3.10.7
  percent_indicator: ^4.2.3
  permission_handler: ^11.3.1
  postgrest: ^2.4.2
  photo_view: ^0.14.0
  printing: ^5.12.0
  provider: ^6.1.1
  mobile_scanner: ^5.0.1
  rive: ^0.12.4
  sensors_plus: ^4.0.2
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  supabase: ^2.2.2
  supabase_flutter: ^2.3.4
  timeago: ^3.6.1
  url_launcher: ^6.2.4
  uuid: ^4.3.3
  vector_math: ^2.1.4
  video_player: ^2.8.2
  webview_flutter: ^4.5.0
  flutter_inappwebview: ^6.1.5
  fluttertoast: ^8.2.12

  crypto: any
  flutter_cache_manager: any
  qr_flutter: ^4.1.0
  json_annotation: ^4.9.0
dev_dependencies:
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/videos/
    - assets/animations/
    - assets/models/
    - .env

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/sama.png"
  adaptive_icon_background: "#1565C0"
  adaptive_icon_foreground: "assets/icons/sama_no_background.png"

flutter_native_splash:
  # Professional SAMA branding colors matching AccountantThemeConfig
  color: "#0A0A0A"  # Luxury black background
  color_dark: "#0A0A0A"  # Same for dark mode

  # SAMA logo for splash screen
  image: assets/images/sama.png
  image_dark: assets/images/sama.png

  # Platform support
  android: true
  ios: true
  web: true

  # Professional splash screen settings
  android_gravity: center
  ios_content_mode: center
  web_image_mode: center

  # Responsive sizing for different screen densities
  android_12:
    image: assets/images/sama.png
    color: "#0A0A0A"

  # Full screen splash for modern Android
  fullscreen: true

  # Info.plist modifications for iOS
  info_plist_files:
    - 'ios/Runner/Info.plist'

